First pass at upgrading to UNIX sockets
This commit removes the old TCP scheme
between portal and bourreaux, and replace it with
a similar one based on UNIX domain sockets. These
are still forwarded by a SSH master.

I ripped out the capability to connect to a second-level
submit host, however. The remote host we connect to, where
the Bourreau runs, is assumed to have the ability to submit
jobs.

diff --git a/Bourreau/script/cbrain_remote_ctl b/Bourreau/script/cbrain_remote_ctl
--- a/Bourreau/script/cbrain_remote_ctl
+++ b/Bourreau/script/cbrain_remote_ctl
@@ -1,9 +1,9 @@
-#!/bin/bash
+#!/usr/bin/env ruby
 
 #
 # CBRAIN Project
 #
-# Copyright (C) 2008-2020
+# Copyright (C) 2008-2021
 # The Royal Institution for the Advancement of Learning
 # McGill University
 #
@@ -21,95 +21,218 @@
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
 
+
+
+# This script is a wrapper that launches the normal Rails server,
+# but with the added ability of receiving the content of the database.yml
+# file in standard output before it does so. Also, once the server is
+# started, the database.yml is deleted outright, closing a security hole.
 #
-# This small wrapper is a replacement for the
-# 'establish a secondary tunnel to submit host'
-# feature of cbrain_remote_ctl_rb (which was the
-# original content of this file here, but required
-# a lot more ruby libs). Since in the case where
-# we need a secondary tunnel, we are often on a
-# very plain login node, this script requires no
-# ruby and just works with plain bash commands.
-# In MOST situations in fact, this script's content
-# is not used and the arguments are completely all
-# delegated to the original cbrain_remote_ctl_rb.
+# This script it NOT usually executed by a human, instead it is
+# invoked by the Portal when trying to start or stop a Bourreau.
 #
+# The command-line args are to be provided strictly in the order shown
+# below, and all of them should be present (this is done simply so that
+# this bash script is kept simple, as anyway this script is not meant
+# to be started manually by users).
+#
+#
+# To start the Rails app:
+#
+#   $0 start -e <environment>
+#
+# which will result in reading the database.yml from stdin, installing
+# it, executing this command
+#
+#   puma --config config/puma.rb
+#
+# and finally removing the database.yml file. Any database.yml file
+# already present before doing all this will be erased.
+#
+#
+# To stop the Rails app:
+#
+#   $0 stop
+#
+# which will result in killing the rails app.
+#
+#
+# To start a console
+#
+#   $0 console -e <environment>
 
-this_script=$(readlink -e "$0" 2>/dev/null)
-# On non-linux, "readlink -e" doesn't exist... :-(
-if test -z "$this_script" ; then
-  this_script="$0"
-  if [[ "$this_script" != /* ]] ; then
-    this_script="$PWD/$this_script" # good enough
-  fi
-fi
-this_script_dir=$(dirname $this_script)
 
-# This is the most common case
-if test "$#" -lt 6 -o "X$1" != "X-R" -o "X$3" != "X-H" -o "X$5" != "X-D" ; then
-  echo "Transfering control from $this_script to cbrain_remote_ctl_rb"
-  exec "$this_script_dir"/cbrain_remote_ctl_rb "$@"
-  exit 10 # should never get here
-fi
 
-# The less common case: we are on a plain login node with
-# none of the ruby libs needed by cbrain_remote_ctl_rb.
+#require 'rubygems'
+#require 'active_support'
+#require 'active_support/core_ext.rb'
+#require 'etc'
+#require File.dirname(__FILE__) + '/../lib/cbrain_file_revision.rb' # ugly
+#require File.dirname(__FILE__) + '/../lib/cbrain_extensions/string_extensions/utilities.rb' # SO UGLEEEEE!!!!
+#require File.dirname(__FILE__) + '/../config/initializers/added_core_extensions/string.rb' # ugly
 
-# Arguments all have a hardcoded index number in this mode.
-remhost="$2"
-httpport="$4"
-dbport="$6"
-myhost=$(hostname)
-shift 6
 
-umask 077 # for socket access permissions
-controlsocket="/tmp/cbrain-login-to-submit.sock"
+#########################
+# S U B R O U T I N E S #
+#########################
 
-if test -S $controlsocket ; then
-  echo "Found existing master from login host $myhost to backend $remhost"
-  if ! ssh -N -o ControlPath=$controlsocket -O check $remhost ; then
-    echo "The master seems to be dead, removing socket"
-    rm -f $controlsocket
-  fi
-fi
+# Usage
+def usage(basename)
+    puts "Usage: #{basename} start -e <environment>\n" +
+         "       #{basename} stop\n" +
+         "       #{basename} console -e <environment>"
+    Kernel.exit(10)
+end
 
-if ! test -S $controlsocket ; then
-  echo "Establishing new master from login host $myhost to backend $remhost"
-  ssh -A -f -n -N -x                     \
-    -o BatchMode=yes                     \
-    -o ControlMaster=yes                 \
-    -o ControlPath=$controlsocket        \
-    -o ExitOnForwardFailure=yes          \
-    -L ${httpport}:localhost:${httpport} \
-    -R ${dbport}:localhost:${dbport}     \
-    -p 22                                \
-    $remhost
+# Fatal error message
+def fatal(message)
+    puts message
+    Kernel.exit(20)
+end
 
-  ssh_status=$?
-  if test $ssh_status -gt 0 ; then
-    echo "Could not start SSH master: status $ssh_status" 1>&2
-    exit $ssh_status
-  fi
-fi
+# Run-time paths
+cwd      = Dir.getwd
+basename = $PROGRAM_NAME
+fullprog = basename =~ /^\// ? basename : cwd + "/" + basename
 
-# Invoke the RB version of the control script, on the remote side, using
-# the master. The current STDIN will be connected to the remote
-# STDIN for transmission of the DB config file, if necessary.
-ssh -A -x                               \
-    -o ExitOnForwardFailure=true        \
-    -o ControlMaster=no                 \
-    -o ControlPath=$controlsocket       \
-    $remhost                            \
-    "cd \"$this_script_dir\"; bundle exec \"$this_script\"_rb $@ 2>&1"
+# Rails-specific paths
+rails_home = fullprog.sub(/\/script\/.+$/,"")
+pidfile    = "#{rails_home}/tmp/pids/server.pid"
 
-# If the main command ($1) is "stop", we also stop the local master
-if test "X$1" = "Xstop" ; then
-  echo "Stopping master from login host $myhost to backend $remhost"
-  # This is nice, this -O option for controlling the master
-  ssh -n -N -x \
-    -o ControlPath=$controlsocket \
-    -O exit                       \
-    $remhost
-fi
+# To help diagnose problems, print Ruby's version.
+puts "You are using Ruby #{RUBY_VERSION}"
+if RUBY_VERSION =~ /^1\.[0-8]/
+  puts "Warning! This Ruby version seems to be way too old. Maybe your environment wasn't initialized properly?"
+end
 
-exit 0
+# Check usage
+usage(basename) if ARGV.size != 1 && ARGV.size != 3 && ARGV.size != 5    # 1, 3 or 5 args!
+
+#############################################################
+# STOP
+#############################################################
+
+if ARGV.size == 1
+    usage(basename) if ARGV[0] != "stop"
+    fp = File.open(pidfile,"r") rescue nil
+    if fp
+        pid = fp.read.to_i
+        fp.close
+        Process.kill("TERM", pid)
+        puts "Bourreau Stopped"
+        Kernel.exit(0)
+    end
+    fatal "Could not find/open PID file '#{pidfile}'."
+end
+
+#############################################################
+# ARGUMENT CHECKS FOR OTHER MODES (start or console)
+#############################################################
+
+if ARGV[0] == "start"      # start -e env
+  usage(basename) if ARGV.size != 3 || ARGV[1] != "-e"
+elsif ARGV[0] == "console" # console -e env
+  usage(basename) if ARGV.size != 3 || ARGV[1] != "-e"
+else
+  usage(basename)
+end
+mode = ARGV[0] # 'start' or 'console'
+
+if mode == "start" && File.exist?(pidfile)
+  pid = File.read(pidfile).to_i
+  # The command below echoes back the PID if the process exists,
+  # and happens to work on both Linux and MacOS.
+  exists = `ps -p #{pid} -o pid=`
+  if exists.match /\d+/
+    fatal("The Rails app seems to be running already (PID=#{pid}). Kill it first.")
+  end
+  File.unlink(pidfile) rescue true
+end
+
+# Check arguments
+environment = ARGV[2]
+fatal("Environment argument must be 'production', 'development' or 'test'") unless
+   environment =~ /^(production|development|test)$/
+
+db_yml_text = mode == "start" ? (STDIN.read || "") : ""
+db_file     = rails_home + "/config/database.yml"
+
+# Install or restore database.yml if necessary
+blank_yml  = db_yml_text !~ /\S/
+
+if blank_yml #  blank? use what db.yml is already here
+  if ! File.exist?(db_file)
+    fatal("Could not find a database.yml file for the Rails application!")
+  end
+else # db text is provided to us
+  # Substitute most recently created DB socket filename
+  sockfiles = Dir.glob("#{rails_home}/tmp/sockets/db.*.sock").map { |f| Pathname.new(f) }
+  fatal("Could not find a DB socket in tmp/sockets/db.*.sock") if sockfiles.size == 0
+  sockfiles.sort! { |sock_a,sock_b| sock_a.mtime <=> sock_b.mtime } # order by time
+  db_sockfile = sockfiles.pop.to_s # remove the last, which is the most recent
+  db_yml_text.sub!(/socket:.*/,"socket: #{db_sockfile}")
+  File.open(db_file,"w") { |fh| fh.write(db_yml_text) }
+  sockfiles.each { |f| File.unlink(f) rescue nil } # remove all older socket files
+end
+
+###########################################
+# CONSOLE START
+###########################################
+if mode == 'console'
+  Dir.chdir(rails_home) do
+    # Bash command for launching the interactive console
+    start_success = system("script/rails", "console", environment) # this will BLOCK
+    File.unlink(db_file) rescue true
+    puts "\nBourreau Console Exited."
+    Kernel.exit(start_success ? 0 : 10) # all done
+  end
+end
+
+###########################################
+# BOURREAU START
+###########################################
+
+# Rename log files when they are too big
+date_extension       = Time.now.strftime("%Y-%m-%d")
+start_log_file       = "#{rails_home}/log/server_start.log"
+environment_log_file = "#{rails_home}/log/#{environment}.log"
+if File.exists?( start_log_file ) && File.size( start_log_file ) > 1_048_576
+  File.rename(start_log_file, start_log_file.sub(/\.log$/,"_#{date_extension}.log"))
+end
+if File.exists?( environment_log_file ) && File.size( environment_log_file ) > 1_048_576
+  File.rename(environment_log_file, environment_log_file.sub(/\.log$/,"_#{date_extension}.log"))
+end
+
+# Start the server
+start_success=false
+Dir.chdir(rails_home) do
+  # We provide a dummy value for the session cookie encoder.
+  # TODO just documet in YAML file?
+  ENV["SECRET_KEY_BASE"] ||= "JUNK-NOT-USED-IN-BOURREAU-THERE-ARE-NO-SESSIONS-ANYWAY"
+  # puma_wait_wrapper is a custom program that boots puma and waits to make sure
+  start_success = system("script/puma_wait_wrapper")
+end
+
+# If we were provided with a database.yml, we need
+# delete it once the server has read it.
+if (! blank_yml)
+  File.unlink(db_file) rescue true
+end
+
+# Return a message to indicate to our calling context
+# whether or not the server started.
+if start_success
+  puts "Bourreau Started." # This string is used by the Portal controller!
+  Kernel.exit(0)
+end
+
+puts "Bourreau Failed."
+puts "Raw BASH command: #{raw_system_cmd}"
+#if File.exists?(start_log_file)
+#  puts "Here are the last 100 lines of the server's log:"
+#  system("tail -100 '#{start_log_file}'")
+#else
+#  puts "No server log file found to help you out of this one :-("
+#end
+Kernel.exit(10)
+
